services:
  timer:
    build: '.'
    restart: unless-stopped
    container_name: timer-bot
    env_file:
      .env
    volumes:
      - type: bind
        source: ./bot.sqlite
        target: /data/bot.sqlite
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.timer-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.timer-secure.entrypoints=websecure"
      - "traefik.http.routers.timer-secure.tls=true"
      - "traefik.http.routers.timer-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.timer-secure.loadbalancer.server.port=80"
    networks:
      - web
volumes:
  data:
networks:
  web:
    external: true
